import React, { useState, useEffect } from 'react'
import { BrowserRouter, Routes, Route, NavLink, Navigate, useNavigate, Outlet } from 'react-router-dom'
import { AuthProvider, useAuth } from './lib/auth'
import { MarketProvider, useMarket } from './lib/useMarket.jsx'
import ProtectedRoute from './components/ProtectedRoute'
import PaywallGate from './components/PaywallGate'
import AIChat from './components/AIChat'
import Onboarding from './components/Onboarding'
import LandingPage from './pages/LandingPage'
import AuthCallback from './pages/AuthCallback'
import AdminLogin from './pages/AdminLogin'
import Admin from './pages/Admin'
import Overview from './pages/Overview'
import Signals from './pages/Signals'
import Journal from './pages/Journal'
import Portfolio from './pages/Portfolio'
import { supabase } from './lib/supabase'
